[package]
name = "projections"
version = "0.1.0"
edition = "2024"

[dependencies]
egui_deferred_table = { path = "../.." }
shared = { path = "../shared" }

egui = { version = "0.33.0" }
eframe = { version = "0.33.0"}

# logging
env_logger = "0.11.8"
log = "0.4.28"

